<?xml version="1.0"?>
<robot name="flexible_cable"
    xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="N" value="10"/>
    <xacro:property name="length" value="1" />
    <xacro:property name="mass" value="0.01" />
    <xacro:property name="seg_length" value="${length/N}" />
    <xacro:property name="seg_mass" value="${mass/N}" />
    <xacro:property name="cable_radius" value="0.002" />
    <xacro:property name="color" value="Yellow"/>

    <!-- MACRO: dummy link to create 3D rotation (in Euler Angles) -->
    <xacro:macro name="dummy_link" params="name">
        <link name="${name}">
            <gravity>0</gravity>
            <inertial>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <mass value="0.00001"/>
                <inertia ixx="0.000000001" ixy="0" ixz="0" iyy="0.000000001" iyz="0" izz="0.000000001"/>
            </inertial>
            <visual>
                <geometry>
                    <sphere radius="0.00001"/>
                </geometry>
            </visual>
        </link>
        <gazebo reference="${name}">
            <material>Gazebo/Black</material>
        </gazebo>
    </xacro:macro>
    <!-- MACRO: create a rotational joint ( TODO: debug this joint) -->
    <xacro:macro name="rotational_joint" params="parent child jx jy jz">
        <xacro:dummy_link name="${parent}_${child}_dummylink1"/>
        <xacro:dummy_link name="${parent}_${child}_dummylink2"/>
        <joint name="${parent}_${child}_roll" type="continuous">
            <parent link="${parent}"/>
            <child link="${parent}_${child}_dummylink1"/>
            <axis xyz="1 0 0"/>
            <joint_properties damping="0.0" friction="0.0" />
            <origin xyz="${jx} ${jy} ${jz}"/>
        </joint>
        <joint name="${parent}_${child}_pitch" type="continuous">
            <parent link="${parent}_${child}_dummylink1"/>
            <child link="${parent}_${child}_dummylink2"/>
            <axis xyz="0 1 0"/>
            <joint_properties damping="0.0" friction="0.0" />
            <origin xyz="0 0 0"/>
        </joint>
        <joint name="${parent}_${child}_yaw" type="continuous">
            <parent link="${parent}_${child}_dummylink2"/>
            <child link="${child}"/>
            <axis xyz="0 0 1"/>
            <joint_properties damping="0.0" friction="0.0" />
            <origin xyz="0 0 0"/>
        </joint>
    </xacro:macro>
    <xacro:macro name="cable_segment" params="index">
        <link name="segment${index}">
            <collision>
                <origin xyz="0 0 ${seg_length/2}" rpy="0 0 0"/>
                <geometry>
                    <cylinder length="${seg_length}" radius="${cable_radius}"/>
                </geometry>
            </collision>
            <visual>
                <origin xyz="0 0 ${seg_length/2}" rpy="0 0 0"/>
                <geometry>
                    <cylinder length="${seg_length}" radius="${cable_radius}"/>
                </geometry>
            </visual>
            <inertial>
                <origin xyz="0 0 ${seg_length/2}" rpy="0 0 0"/>
                <mass value="${seg_mass}"/>
                <!-- TODO fix the inertia -->
                <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0004"/>
            </inertial>
        </link>
        <gazebo reference="segment${index}">
            <material>Gazebo/${color}</material>
            <kp>10.0</kp>
            <kd>1</kd>
            <mu1>1.0</mu1>
            <mu2>1.0</mu2>
            <maxVel>0.0</maxVel>
            <minDepth>0.001</minDepth>
            <collision>
                <max_contacts>10</max_contacts>
                <surface>
                    <bounce>
                        <restitution_coefficient>0.0</restitution_coefficient>
                        <threshold>0.01</threshold>
                    </bounce>
                </surface>
            </collision>
        </gazebo>
    </xacro:macro>


    <xacro:cable_segment index="1"/>
    <xacro:cable_segment index="2"/>
    <xacro:rotational_joint parent="segment1" child="segment2" jx="0" jy="0" jz="${seg_length}"/>
    <xacro:cable_segment index="3"/>
    <xacro:rotational_joint parent="segment2" child="segment3" jx="0" jy="0" jz="${seg_length}"/>
    <xacro:cable_segment index="4"/>
    <xacro:rotational_joint parent="segment3" child="segment4" jx="0" jy="0" jz="${seg_length}"/>
    <xacro:cable_segment index="5"/>
    <xacro:rotational_joint parent="segment4" child="segment5" jx="0" jy="0" jz="${seg_length}"/>
    <xacro:cable_segment index="6"/>
    <xacro:rotational_joint parent="segment5" child="segment6" jx="0" jy="0" jz="${seg_length}"/>
    <xacro:cable_segment index="7"/>
    <xacro:rotational_joint parent="segment6" child="segment7" jx="0" jy="0" jz="${seg_length}"/>
    <xacro:cable_segment index="8"/>
    <xacro:rotational_joint parent="segment7" child="segment8" jx="0" jy="0" jz="${seg_length}"/>
    <xacro:cable_segment index="9"/>
    <xacro:rotational_joint parent="segment8" child="segment9" jx="0" jy="0" jz="${seg_length}"/>
    <xacro:cable_segment index="10"/>
    <xacro:rotational_joint parent="segment9" child="segment10" jx="0" jy="0" jz="${seg_length}"/>



</robot>