<?xml version="1.0"?>
<robot name="payload"
    xmlns:xacro="http://ros.org/wiki/xacro">
    <!-- Properties -->
    <!-- load dimensions -->
    <xacro:property name="load_mass" value="2" />
    <xacro:property name="load_length" value="0.5" />
    <xacro:property name="load_width" value="0.5" />
    <xacro:property name="load_height" value="0.2" />
    <xacro:property name="cable_length" value="1" />
    <xacro:property name="cable_radius" value="0.002" />

    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:include filename="$(find qrotor_gazebo)/xacro/qrotor_gazebo.xacro"/>

    <!-- Base Link -->
    <link name="payload_link">
        <collision>
            <origin xyz="0 0 ${load_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${load_length} ${load_width} ${load_height}"/>
            </geometry>
            <surface>
                <bounce restitution_coefficient = "0"/>
            </surface>
        </collision>
        <visual>
            <origin xyz="0 0 ${load_height/2}" rpy="0 0 ${-PI/2}"/>
            <geometry>
                <mesh filename="file:///$(find qrotor_description)/meshes/arcuo.dae" scale="${load_length*0.5} ${load_width*0.5} ${load_height*0.5}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <inertial>
            <origin xyz="0 0 ${load_height/2}" rpy="0 0 0"/>
            <mass value="${load_mass}"/>
            <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.4"/>
        </inertial>
    </link>
    <xacro:rigidbody_plugin namespace="payload" parent_link="payload_link"/>


</robot>
