<?xml version="1.0"?>
<robot name="spherical_pendulum"
    xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Constants for robot dimensions -->
    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="mass" value="1" />
    <xacro:property name="base_width" value="0.5" />
    <xacro:property name="base_length" value="0.5" />
    <xacro:property name="base_height" value="0.2" />
    <xacro:property name="cable_length" value="1" />
    <xacro:property name="cable_radius" value="0.002" />


    <!-- Used for fixing robot to Gazebo 'base_link' -->
    <link name="world"/>

    <joint name="fixed" type="fixed">
        <parent link="world"/>
        <child link="fixed_base"/>
    </joint>

    <!-- Base Link -->
    <link name="fixed_base">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${mass}"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
        </inertial>
    </link>

    <!-- MACRO: dummy link to create 3D rotation (in Euler Angles) -->
    <xacro:macro name="dummy_link" params="name">
        <link name="${name}">
            <gravity>0</gravity>
            <inertial>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <mass value="0.00001"/>
                <inertia ixx="0.000000001" ixy="0" ixz="0" iyy="0.000000001" iyz="0" izz="0.000000001"/>
            </inertial>
            <visual>
                <geometry>
                    <sphere radius="0.001"/>
                </geometry>
            </visual>
        </link>
        <gazebo reference="${name}">
            <material>Gazebo/Black</material>
        </gazebo>
    </xacro:macro>

    <!-- MACRO: create a rotational joint ( TODO: debug this joint) -->
    <xacro:macro name="rotational_joint" params="parent child jx jy jz r p y">
        <xacro:dummy_link name="${parent}_${child}_dummylink1"/>
        <xacro:dummy_link name="${parent}_${child}_dummylink2"/>
        <joint name="${parent}_${child}_roll" type="continuous">
            <parent link="${parent}"/>
            <child link="${parent}_${child}_dummylink1"/>
            <axis xyz="1 0 0"/>
            <!-- <limit effort="1000.0" lower="0.0" upper="0.548" velocity="0.5"/> -->
            <dynamics damping="0.0" friction="0.0"/>
            <!-- <limit effort="30" velocity="1.0" lower="-2.2" upper="0.7" />
            <safety_controller k_velocity="10" k_position="15" soft_lower_limit="-2.0" soft_upper_limit="0.5" /> -->
            <!-- <joint_properties damping="0.0" friction="0.0" /> -->
            <origin xyz="${jx} ${jy} ${jz}" rpy="${r} 0 0"/>
        </joint>
        <joint name="${parent}_${child}_pitch" type="continuous">
            <parent link="${parent}_${child}_dummylink1"/>
            <child link="${parent}_${child}_dummylink2"/>
            <axis xyz="0 1 0"/>

            <!-- <limit effort="1000.0" lower="0.0" upper="0.548" velocity="0.5"/> -->
            <dynamics damping="0.0" friction="0.0"/>
            <!-- <dynamics damping="0.0" friction="0.0"/>
            <limit effort="30" velocity="1.0" lower="-2.2" upper="0.7" />
            <safety_controller k_velocity="10" k_position="15" soft_lower_limit="-2.0" soft_upper_limit="0.5" /> -->
            <!-- <joint_properties damping="0.0" friction="0.0" /> -->
            <origin xyz="0 0 0" rpy="0 ${p} 0"/>
        </joint>
        <joint name="${parent}_${child}_yaw" type="continuous">
            <parent link="${parent}_${child}_dummylink2"/>
            <child link="${child}"/>
            <axis xyz="0 0 1"/>

            <!-- <limit effort="1000.0" lower="0.0" upper="0.548" velocity="0.5"/> -->
            <dynamics damping="0.0" friction="0.0"/>
            <!-- <dynamics damping="0.0" friction="0.0"/> -->
            <!-- <limit effort="30" velocity="1.0" lower="-2.2" upper="0.7" /> -->
            <!-- <safety_controller k_velocity="10" k_position="15" soft_lower_limit="-2.0" soft_upper_limit="0.5" /> -->
            <!-- <joint_properties damping="0.0" friction="0.0" /> -->
            <origin xyz="0 0 0" rpy="0 0 ${y}"/>
        </joint>
    </xacro:macro>

    <link name="cable">
        <collision>
            <origin xyz="0 0 ${cable_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${cable_length}" radius="${cable_radius}"/>
            </geometry>
            <surface>
                <bounce restitution_coefficient = "0"/>
            </surface>
        </collision>
        <visual>
            <origin xyz="0 0 ${cable_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${cable_length}" radius="${2*cable_radius}"/>
            </geometry>
        </visual>
        <inertial>
            <origin xyz="0 0 ${cable_length/2}" rpy="0 0 0"/>
            <mass value="5"/>
            <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0004"/>
        </inertial>
    </link>
    <gazebo reference="cable">
        <material>Gazebo/Black</material>
        <self_collide>0</self_collide>
    </gazebo>

    <!-- <joint name="revolute1" type="continuous">
        <parent link="fixed_base"/>
        <child link="cable"/>
        <axis xyz="0 1 0"/>
        <origin xyz="0 0 ${-0.5*base_height}" rpy="0 ${PI/2} 0"/>
    </joint> -->

    <!-- <physics type='ode'>
        <stepTime>0.0001</stepTime>
    </physics> -->
    <xacro:rotational_joint parent="fixed_base" child="cable" jx="0" jy="0" jz="${-base_height/2}" r="${PI/2}" p="${PI/4}" y="${PI/4}"/>

    <!-- <joint:universal name="universal_joint">
        <body1>"fixed_base"</body1>
        <body2>"cable"</body2>
        <anchor>"fixed_base"</anchor>
        <axis1>1 0 0</axis1>
        <axis2>0 1 0</axis2>
    </joint:universal> -->

</robot>