//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the qrotor_ground package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __qrotor_ground__DRONECOMMANDSCONFIG_H__
#define __qrotor_ground__DRONECOMMANDSCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace qrotor_ground
{
  class DroneCommandsConfigStatics;

  class DroneCommandsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(DroneCommandsConfig &config, const DroneCommandsConfig &max, const DroneCommandsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const DroneCommandsConfig &config1, const DroneCommandsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, DroneCommandsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const DroneCommandsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, DroneCommandsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const DroneCommandsConfig &config) const = 0;
      virtual void getValue(const DroneCommandsConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T DroneCommandsConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T DroneCommandsConfig::* field;

      virtual void clamp(DroneCommandsConfig &config, const DroneCommandsConfig &max, const DroneCommandsConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const DroneCommandsConfig &config1, const DroneCommandsConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, DroneCommandsConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const DroneCommandsConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, DroneCommandsConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const DroneCommandsConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const DroneCommandsConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, DroneCommandsConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, DroneCommandsConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<DroneCommandsConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(DroneCommandsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("mode"==(*_i)->name){mode = boost::any_cast<int>(val);}
        if("x"==(*_i)->name){x = boost::any_cast<double>(val);}
        if("y"==(*_i)->name){y = boost::any_cast<double>(val);}
        if("z"==(*_i)->name){z = boost::any_cast<double>(val);}
        if("yaw"==(*_i)->name){yaw = boost::any_cast<double>(val);}
        if("send"==(*_i)->name){send = boost::any_cast<bool>(val);}
        if("activate_mission"==(*_i)->name){activate_mission = boost::any_cast<bool>(val);}
        if("kill_mission"==(*_i)->name){kill_mission = boost::any_cast<bool>(val);}
      }
    }

    int mode;
double x;
double y;
double z;
double yaw;
bool send;
bool activate_mission;
bool kill_mission;

    bool state;
    std::string name;

    class CMDS
{
  public:
    CMDS()
    {
      state = true;
      name = "CMDs";
    }

    void setParams(DroneCommandsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("kill"==(*_i)->name){kill = boost::any_cast<bool>(val);}
        if("arm"==(*_i)->name){arm = boost::any_cast<bool>(val);}
        if("disarm"==(*_i)->name){disarm = boost::any_cast<bool>(val);}
        if("takeoff"==(*_i)->name){takeoff = boost::any_cast<bool>(val);}
        if("land"==(*_i)->name){land = boost::any_cast<bool>(val);}
        if("OFFBOARD"==(*_i)->name){OFFBOARD = boost::any_cast<bool>(val);}
      }
    }

    bool kill;
bool arm;
bool disarm;
bool takeoff;
bool land;
bool OFFBOARD;

    bool state;
    std::string name;

    
}cmds;

}groups;



//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int mode;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double x;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double y;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double z;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double yaw;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool send;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool activate_mission;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool kill_mission;
//#line 18 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      bool kill;
//#line 19 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      bool arm;
//#line 20 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      bool disarm;
//#line 21 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      bool takeoff;
//#line 22 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      bool land;
//#line 23 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      bool OFFBOARD;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("DroneCommandsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const DroneCommandsConfig &__max__ = __getMax__();
      const DroneCommandsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const DroneCommandsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const DroneCommandsConfig &__getDefault__();
    static const DroneCommandsConfig &__getMax__();
    static const DroneCommandsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const DroneCommandsConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void DroneCommandsConfig::ParamDescription<std::string>::clamp(DroneCommandsConfig &config, const DroneCommandsConfig &max, const DroneCommandsConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class DroneCommandsConfigStatics
  {
    friend class DroneCommandsConfig;

    DroneCommandsConfigStatics()
    {
DroneCommandsConfig::GroupDescription<DroneCommandsConfig::DEFAULT, DroneCommandsConfig> Default("Default", "", 0, 0, true, &DroneCommandsConfig::groups);
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.mode = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.mode = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.mode = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DroneCommandsConfig::AbstractParamDescriptionConstPtr(new DroneCommandsConfig::ParamDescription<int>("mode", "int", 0, "A drone command mode", "{'enum': [{'name': 'Move', 'type': 'int', 'value': 0, 'srcline': 7, 'srcfile': '/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg', 'description': 'Move drone by', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'Setpoint', 'type': 'int', 'value': 1, 'srcline': 8, 'srcfile': '/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg', 'description': 'Move drone to setpoint', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Command setpoint to drone'}", &DroneCommandsConfig::mode)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DroneCommandsConfig::AbstractParamDescriptionConstPtr(new DroneCommandsConfig::ParamDescription<int>("mode", "int", 0, "A drone command mode", "{'enum': [{'name': 'Move', 'type': 'int', 'value': 0, 'srcline': 7, 'srcfile': '/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg', 'description': 'Move drone by', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'Setpoint', 'type': 'int', 'value': 1, 'srcline': 8, 'srcfile': '/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg', 'description': 'Move drone to setpoint', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Command setpoint to drone'}", &DroneCommandsConfig::mode)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.x = -2.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.x = 2.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.x = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DroneCommandsConfig::AbstractParamDescriptionConstPtr(new DroneCommandsConfig::ParamDescription<double>("x", "double", 0, "x in meters", "", &DroneCommandsConfig::x)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DroneCommandsConfig::AbstractParamDescriptionConstPtr(new DroneCommandsConfig::ParamDescription<double>("x", "double", 0, "x in meters", "", &DroneCommandsConfig::x)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.y = -2.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.y = 2.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.y = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DroneCommandsConfig::AbstractParamDescriptionConstPtr(new DroneCommandsConfig::ParamDescription<double>("y", "double", 0, "y in meters", "", &DroneCommandsConfig::y)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DroneCommandsConfig::AbstractParamDescriptionConstPtr(new DroneCommandsConfig::ParamDescription<double>("y", "double", 0, "y in meters", "", &DroneCommandsConfig::y)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.z = -2.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.z = 3.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.z = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DroneCommandsConfig::AbstractParamDescriptionConstPtr(new DroneCommandsConfig::ParamDescription<double>("z", "double", 0, "z in meters", "", &DroneCommandsConfig::z)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DroneCommandsConfig::AbstractParamDescriptionConstPtr(new DroneCommandsConfig::ParamDescription<double>("z", "double", 0, "z in meters", "", &DroneCommandsConfig::z)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.yaw = -180.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.yaw = 180.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.yaw = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DroneCommandsConfig::AbstractParamDescriptionConstPtr(new DroneCommandsConfig::ParamDescription<double>("yaw", "double", 0, "yaw in degrees", "", &DroneCommandsConfig::yaw)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DroneCommandsConfig::AbstractParamDescriptionConstPtr(new DroneCommandsConfig::ParamDescription<double>("yaw", "double", 0, "yaw in degrees", "", &DroneCommandsConfig::yaw)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.send = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.send = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.send = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DroneCommandsConfig::AbstractParamDescriptionConstPtr(new DroneCommandsConfig::ParamDescription<bool>("send", "bool", 0, "Send Command", "", &DroneCommandsConfig::send)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DroneCommandsConfig::AbstractParamDescriptionConstPtr(new DroneCommandsConfig::ParamDescription<bool>("send", "bool", 0, "Send Command", "", &DroneCommandsConfig::send)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.activate_mission = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.activate_mission = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.activate_mission = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DroneCommandsConfig::AbstractParamDescriptionConstPtr(new DroneCommandsConfig::ParamDescription<bool>("activate_mission", "bool", 0, "Send activate mission Command", "", &DroneCommandsConfig::activate_mission)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DroneCommandsConfig::AbstractParamDescriptionConstPtr(new DroneCommandsConfig::ParamDescription<bool>("activate_mission", "bool", 0, "Send activate mission Command", "", &DroneCommandsConfig::activate_mission)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.kill_mission = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.kill_mission = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.kill_mission = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DroneCommandsConfig::AbstractParamDescriptionConstPtr(new DroneCommandsConfig::ParamDescription<bool>("kill_mission", "bool", 0, "Send kill mission Command", "", &DroneCommandsConfig::kill_mission)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DroneCommandsConfig::AbstractParamDescriptionConstPtr(new DroneCommandsConfig::ParamDescription<bool>("kill_mission", "bool", 0, "Send kill mission Command", "", &DroneCommandsConfig::kill_mission)));
DroneCommandsConfig::GroupDescription<DroneCommandsConfig::DEFAULT::CMDS, DroneCommandsConfig::DEFAULT> CMDs("CMDs", "tab", 0, 1, true, &DroneCommandsConfig::DEFAULT::cmds);
//#line 18 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      __min__.kill = 0;
//#line 18 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      __max__.kill = 1;
//#line 18 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      __default__.kill = 0;
//#line 18 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      CMDs.abstract_parameters.push_back(DroneCommandsConfig::AbstractParamDescriptionConstPtr(new DroneCommandsConfig::ParamDescription<bool>("kill", "bool", 0, "Send Kill Command", "", &DroneCommandsConfig::kill)));
//#line 18 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      __param_descriptions__.push_back(DroneCommandsConfig::AbstractParamDescriptionConstPtr(new DroneCommandsConfig::ParamDescription<bool>("kill", "bool", 0, "Send Kill Command", "", &DroneCommandsConfig::kill)));
//#line 19 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      __min__.arm = 0;
//#line 19 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      __max__.arm = 1;
//#line 19 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      __default__.arm = 0;
//#line 19 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      CMDs.abstract_parameters.push_back(DroneCommandsConfig::AbstractParamDescriptionConstPtr(new DroneCommandsConfig::ParamDescription<bool>("arm", "bool", 0, "Send Arm Command", "", &DroneCommandsConfig::arm)));
//#line 19 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      __param_descriptions__.push_back(DroneCommandsConfig::AbstractParamDescriptionConstPtr(new DroneCommandsConfig::ParamDescription<bool>("arm", "bool", 0, "Send Arm Command", "", &DroneCommandsConfig::arm)));
//#line 20 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      __min__.disarm = 0;
//#line 20 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      __max__.disarm = 1;
//#line 20 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      __default__.disarm = 0;
//#line 20 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      CMDs.abstract_parameters.push_back(DroneCommandsConfig::AbstractParamDescriptionConstPtr(new DroneCommandsConfig::ParamDescription<bool>("disarm", "bool", 0, "Send Disrm Command", "", &DroneCommandsConfig::disarm)));
//#line 20 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      __param_descriptions__.push_back(DroneCommandsConfig::AbstractParamDescriptionConstPtr(new DroneCommandsConfig::ParamDescription<bool>("disarm", "bool", 0, "Send Disrm Command", "", &DroneCommandsConfig::disarm)));
//#line 21 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      __min__.takeoff = 0;
//#line 21 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      __max__.takeoff = 1;
//#line 21 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      __default__.takeoff = 0;
//#line 21 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      CMDs.abstract_parameters.push_back(DroneCommandsConfig::AbstractParamDescriptionConstPtr(new DroneCommandsConfig::ParamDescription<bool>("takeoff", "bool", 0, "Send takeoff Command", "", &DroneCommandsConfig::takeoff)));
//#line 21 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      __param_descriptions__.push_back(DroneCommandsConfig::AbstractParamDescriptionConstPtr(new DroneCommandsConfig::ParamDescription<bool>("takeoff", "bool", 0, "Send takeoff Command", "", &DroneCommandsConfig::takeoff)));
//#line 22 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      __min__.land = 0;
//#line 22 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      __max__.land = 1;
//#line 22 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      __default__.land = 0;
//#line 22 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      CMDs.abstract_parameters.push_back(DroneCommandsConfig::AbstractParamDescriptionConstPtr(new DroneCommandsConfig::ParamDescription<bool>("land", "bool", 0, "Send land Command", "", &DroneCommandsConfig::land)));
//#line 22 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      __param_descriptions__.push_back(DroneCommandsConfig::AbstractParamDescriptionConstPtr(new DroneCommandsConfig::ParamDescription<bool>("land", "bool", 0, "Send land Command", "", &DroneCommandsConfig::land)));
//#line 23 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      __min__.OFFBOARD = 0;
//#line 23 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      __max__.OFFBOARD = 1;
//#line 23 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      __default__.OFFBOARD = 0;
//#line 23 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      CMDs.abstract_parameters.push_back(DroneCommandsConfig::AbstractParamDescriptionConstPtr(new DroneCommandsConfig::ParamDescription<bool>("OFFBOARD", "bool", 0, "Set OFFBOARD CONTROL MODE", "", &DroneCommandsConfig::OFFBOARD)));
//#line 23 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      __param_descriptions__.push_back(DroneCommandsConfig::AbstractParamDescriptionConstPtr(new DroneCommandsConfig::ParamDescription<bool>("OFFBOARD", "bool", 0, "Set OFFBOARD CONTROL MODE", "", &DroneCommandsConfig::OFFBOARD)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      CMDs.convertParams();
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(DroneCommandsConfig::AbstractGroupDescriptionConstPtr(new DroneCommandsConfig::GroupDescription<DroneCommandsConfig::DEFAULT::CMDS, DroneCommandsConfig::DEFAULT>(CMDs)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(DroneCommandsConfig::AbstractGroupDescriptionConstPtr(new DroneCommandsConfig::GroupDescription<DroneCommandsConfig::DEFAULT::CMDS, DroneCommandsConfig::DEFAULT>(CMDs)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(DroneCommandsConfig::AbstractGroupDescriptionConstPtr(new DroneCommandsConfig::GroupDescription<DroneCommandsConfig::DEFAULT, DroneCommandsConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<DroneCommandsConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<DroneCommandsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<DroneCommandsConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    DroneCommandsConfig __max__;
    DroneCommandsConfig __min__;
    DroneCommandsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const DroneCommandsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static DroneCommandsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &DroneCommandsConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const DroneCommandsConfig &DroneCommandsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const DroneCommandsConfig &DroneCommandsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const DroneCommandsConfig &DroneCommandsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<DroneCommandsConfig::AbstractParamDescriptionConstPtr> &DroneCommandsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<DroneCommandsConfig::AbstractGroupDescriptionConstPtr> &DroneCommandsConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const DroneCommandsConfigStatics *DroneCommandsConfig::__get_statics__()
  {
    const static DroneCommandsConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = DroneCommandsConfigStatics::get_instance();

    return statics;
  }

//#line 7 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      const int DroneCommands_Move = 0;
//#line 8 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/DroneCommands.cfg"
      const int DroneCommands_Setpoint = 1;
}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __DRONECOMMANDSRECONFIGURATOR_H__
