//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the qrotor_ground package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __qrotor_ground__MULTIDRONEMANAGERCONFIG_H__
#define __qrotor_ground__MULTIDRONEMANAGERCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace qrotor_ground
{
  class MultiDroneManagerConfigStatics;

  class MultiDroneManagerConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(MultiDroneManagerConfig &config, const MultiDroneManagerConfig &max, const MultiDroneManagerConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const MultiDroneManagerConfig &config1, const MultiDroneManagerConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, MultiDroneManagerConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const MultiDroneManagerConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, MultiDroneManagerConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const MultiDroneManagerConfig &config) const = 0;
      virtual void getValue(const MultiDroneManagerConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T MultiDroneManagerConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T MultiDroneManagerConfig::* field;

      virtual void clamp(MultiDroneManagerConfig &config, const MultiDroneManagerConfig &max, const MultiDroneManagerConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const MultiDroneManagerConfig &config1, const MultiDroneManagerConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, MultiDroneManagerConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const MultiDroneManagerConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, MultiDroneManagerConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const MultiDroneManagerConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const MultiDroneManagerConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, MultiDroneManagerConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, MultiDroneManagerConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<MultiDroneManagerConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(MultiDroneManagerConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("distance"==(*_i)->name){distance = boost::any_cast<double>(val);}
        if("yaw"==(*_i)->name){yaw = boost::any_cast<double>(val);}
        if("set"==(*_i)->name){set = boost::any_cast<bool>(val);}
        if("set_offboard"==(*_i)->name){set_offboard = boost::any_cast<bool>(val);}
      }
    }

    double distance;
double yaw;
bool set;
bool set_offboard;

    bool state;
    std::string name;

    class TRANSLATE
{
  public:
    TRANSLATE()
    {
      state = true;
      name = "Translate";
    }

    void setParams(MultiDroneManagerConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("x"==(*_i)->name){x = boost::any_cast<double>(val);}
        if("y"==(*_i)->name){y = boost::any_cast<double>(val);}
        if("z"==(*_i)->name){z = boost::any_cast<double>(val);}
      }
    }

    double x;
double y;
double z;

    bool state;
    std::string name;

    
}translate;

class OTHER
{
  public:
    OTHER()
    {
      state = true;
      name = "Other";
    }

    void setParams(MultiDroneManagerConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);


      }
    }

    

    bool state;
    std::string name;

    
}other;

class MISSION
{
  public:
    MISSION()
    {
      state = true;
      name = "Mission";
    }

    void setParams(MultiDroneManagerConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("takeoff"==(*_i)->name){takeoff = boost::any_cast<bool>(val);}
        if("landall"==(*_i)->name){landall = boost::any_cast<bool>(val);}
        if("killall"==(*_i)->name){killall = boost::any_cast<bool>(val);}
        if("activate_mission"==(*_i)->name){activate_mission = boost::any_cast<bool>(val);}
        if("kill_mission"==(*_i)->name){kill_mission = boost::any_cast<bool>(val);}
      }
    }

    bool takeoff;
bool landall;
bool killall;
bool activate_mission;
bool kill_mission;

    bool state;
    std::string name;

    
}mission;

}groups;



//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double distance;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double yaw;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool set;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool set_offboard;
//#line 13 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      double x;
//#line 14 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      double y;
//#line 15 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      double z;
//#line 27 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      bool takeoff;
//#line 28 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      bool landall;
//#line 29 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      bool killall;
//#line 30 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      bool activate_mission;
//#line 31 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      bool kill_mission;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("MultiDroneManagerConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const MultiDroneManagerConfig &__max__ = __getMax__();
      const MultiDroneManagerConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const MultiDroneManagerConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const MultiDroneManagerConfig &__getDefault__();
    static const MultiDroneManagerConfig &__getMax__();
    static const MultiDroneManagerConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const MultiDroneManagerConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void MultiDroneManagerConfig::ParamDescription<std::string>::clamp(MultiDroneManagerConfig &config, const MultiDroneManagerConfig &max, const MultiDroneManagerConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class MultiDroneManagerConfigStatics
  {
    friend class MultiDroneManagerConfig;

    MultiDroneManagerConfigStatics()
    {
MultiDroneManagerConfig::GroupDescription<MultiDroneManagerConfig::DEFAULT, MultiDroneManagerConfig> Default("Default", "", 0, 0, true, &MultiDroneManagerConfig::groups);
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.distance = 0.5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.distance = 2.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.distance = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(MultiDroneManagerConfig::AbstractParamDescriptionConstPtr(new MultiDroneManagerConfig::ParamDescription<double>("distance", "double", 0, "distance in meters", "", &MultiDroneManagerConfig::distance)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(MultiDroneManagerConfig::AbstractParamDescriptionConstPtr(new MultiDroneManagerConfig::ParamDescription<double>("distance", "double", 0, "distance in meters", "", &MultiDroneManagerConfig::distance)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.yaw = -180.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.yaw = 180.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.yaw = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(MultiDroneManagerConfig::AbstractParamDescriptionConstPtr(new MultiDroneManagerConfig::ParamDescription<double>("yaw", "double", 0, "yaw in degrees", "", &MultiDroneManagerConfig::yaw)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(MultiDroneManagerConfig::AbstractParamDescriptionConstPtr(new MultiDroneManagerConfig::ParamDescription<double>("yaw", "double", 0, "yaw in degrees", "", &MultiDroneManagerConfig::yaw)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.set = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.set = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.set = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(MultiDroneManagerConfig::AbstractParamDescriptionConstPtr(new MultiDroneManagerConfig::ParamDescription<bool>("set", "bool", 0, "Set Command", "", &MultiDroneManagerConfig::set)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(MultiDroneManagerConfig::AbstractParamDescriptionConstPtr(new MultiDroneManagerConfig::ParamDescription<bool>("set", "bool", 0, "Set Command", "", &MultiDroneManagerConfig::set)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.set_offboard = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.set_offboard = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.set_offboard = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(MultiDroneManagerConfig::AbstractParamDescriptionConstPtr(new MultiDroneManagerConfig::ParamDescription<bool>("set_offboard", "bool", 0, "Set Offboard", "", &MultiDroneManagerConfig::set_offboard)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(MultiDroneManagerConfig::AbstractParamDescriptionConstPtr(new MultiDroneManagerConfig::ParamDescription<bool>("set_offboard", "bool", 0, "Set Offboard", "", &MultiDroneManagerConfig::set_offboard)));
MultiDroneManagerConfig::GroupDescription<MultiDroneManagerConfig::DEFAULT::TRANSLATE, MultiDroneManagerConfig::DEFAULT> Translate("Translate", "", 0, 1, true, &MultiDroneManagerConfig::DEFAULT::translate);
//#line 13 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      __min__.x = -2.0;
//#line 13 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      __max__.x = 2.0;
//#line 13 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      __default__.x = 0.0;
//#line 13 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      Translate.abstract_parameters.push_back(MultiDroneManagerConfig::AbstractParamDescriptionConstPtr(new MultiDroneManagerConfig::ParamDescription<double>("x", "double", 0, "x in meters", "", &MultiDroneManagerConfig::x)));
//#line 13 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      __param_descriptions__.push_back(MultiDroneManagerConfig::AbstractParamDescriptionConstPtr(new MultiDroneManagerConfig::ParamDescription<double>("x", "double", 0, "x in meters", "", &MultiDroneManagerConfig::x)));
//#line 14 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      __min__.y = -2.0;
//#line 14 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      __max__.y = 2.0;
//#line 14 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      __default__.y = 0.0;
//#line 14 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      Translate.abstract_parameters.push_back(MultiDroneManagerConfig::AbstractParamDescriptionConstPtr(new MultiDroneManagerConfig::ParamDescription<double>("y", "double", 0, "y in meters", "", &MultiDroneManagerConfig::y)));
//#line 14 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      __param_descriptions__.push_back(MultiDroneManagerConfig::AbstractParamDescriptionConstPtr(new MultiDroneManagerConfig::ParamDescription<double>("y", "double", 0, "y in meters", "", &MultiDroneManagerConfig::y)));
//#line 15 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      __min__.z = -2.0;
//#line 15 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      __max__.z = 2.0;
//#line 15 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      __default__.z = 1.0;
//#line 15 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      Translate.abstract_parameters.push_back(MultiDroneManagerConfig::AbstractParamDescriptionConstPtr(new MultiDroneManagerConfig::ParamDescription<double>("z", "double", 0, "z in meters", "", &MultiDroneManagerConfig::z)));
//#line 15 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      __param_descriptions__.push_back(MultiDroneManagerConfig::AbstractParamDescriptionConstPtr(new MultiDroneManagerConfig::ParamDescription<double>("z", "double", 0, "z in meters", "", &MultiDroneManagerConfig::z)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Translate.convertParams();
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(MultiDroneManagerConfig::AbstractGroupDescriptionConstPtr(new MultiDroneManagerConfig::GroupDescription<MultiDroneManagerConfig::DEFAULT::TRANSLATE, MultiDroneManagerConfig::DEFAULT>(Translate)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(MultiDroneManagerConfig::AbstractGroupDescriptionConstPtr(new MultiDroneManagerConfig::GroupDescription<MultiDroneManagerConfig::DEFAULT::TRANSLATE, MultiDroneManagerConfig::DEFAULT>(Translate)));
MultiDroneManagerConfig::GroupDescription<MultiDroneManagerConfig::DEFAULT::OTHER, MultiDroneManagerConfig::DEFAULT> Other("Other", "", 0, 2, true, &MultiDroneManagerConfig::DEFAULT::other);
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Other.convertParams();
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(MultiDroneManagerConfig::AbstractGroupDescriptionConstPtr(new MultiDroneManagerConfig::GroupDescription<MultiDroneManagerConfig::DEFAULT::OTHER, MultiDroneManagerConfig::DEFAULT>(Other)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(MultiDroneManagerConfig::AbstractGroupDescriptionConstPtr(new MultiDroneManagerConfig::GroupDescription<MultiDroneManagerConfig::DEFAULT::OTHER, MultiDroneManagerConfig::DEFAULT>(Other)));
MultiDroneManagerConfig::GroupDescription<MultiDroneManagerConfig::DEFAULT::MISSION, MultiDroneManagerConfig::DEFAULT> Mission("Mission", "", 0, 3, true, &MultiDroneManagerConfig::DEFAULT::mission);
//#line 27 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      __min__.takeoff = 0;
//#line 27 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      __max__.takeoff = 1;
//#line 27 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      __default__.takeoff = 0;
//#line 27 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      Mission.abstract_parameters.push_back(MultiDroneManagerConfig::AbstractParamDescriptionConstPtr(new MultiDroneManagerConfig::ParamDescription<bool>("takeoff", "bool", 0, "take_off_all", "", &MultiDroneManagerConfig::takeoff)));
//#line 27 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      __param_descriptions__.push_back(MultiDroneManagerConfig::AbstractParamDescriptionConstPtr(new MultiDroneManagerConfig::ParamDescription<bool>("takeoff", "bool", 0, "take_off_all", "", &MultiDroneManagerConfig::takeoff)));
//#line 28 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      __min__.landall = 0;
//#line 28 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      __max__.landall = 1;
//#line 28 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      __default__.landall = 0;
//#line 28 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      Mission.abstract_parameters.push_back(MultiDroneManagerConfig::AbstractParamDescriptionConstPtr(new MultiDroneManagerConfig::ParamDescription<bool>("landall", "bool", 0, "land_all", "", &MultiDroneManagerConfig::landall)));
//#line 28 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      __param_descriptions__.push_back(MultiDroneManagerConfig::AbstractParamDescriptionConstPtr(new MultiDroneManagerConfig::ParamDescription<bool>("landall", "bool", 0, "land_all", "", &MultiDroneManagerConfig::landall)));
//#line 29 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      __min__.killall = 0;
//#line 29 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      __max__.killall = 1;
//#line 29 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      __default__.killall = 0;
//#line 29 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      Mission.abstract_parameters.push_back(MultiDroneManagerConfig::AbstractParamDescriptionConstPtr(new MultiDroneManagerConfig::ParamDescription<bool>("killall", "bool", 0, "kill_all", "", &MultiDroneManagerConfig::killall)));
//#line 29 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      __param_descriptions__.push_back(MultiDroneManagerConfig::AbstractParamDescriptionConstPtr(new MultiDroneManagerConfig::ParamDescription<bool>("killall", "bool", 0, "kill_all", "", &MultiDroneManagerConfig::killall)));
//#line 30 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      __min__.activate_mission = 0;
//#line 30 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      __max__.activate_mission = 1;
//#line 30 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      __default__.activate_mission = 0;
//#line 30 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      Mission.abstract_parameters.push_back(MultiDroneManagerConfig::AbstractParamDescriptionConstPtr(new MultiDroneManagerConfig::ParamDescription<bool>("activate_mission", "bool", 0, "start and stop mission", "", &MultiDroneManagerConfig::activate_mission)));
//#line 30 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      __param_descriptions__.push_back(MultiDroneManagerConfig::AbstractParamDescriptionConstPtr(new MultiDroneManagerConfig::ParamDescription<bool>("activate_mission", "bool", 0, "start and stop mission", "", &MultiDroneManagerConfig::activate_mission)));
//#line 31 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      __min__.kill_mission = 0;
//#line 31 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      __max__.kill_mission = 1;
//#line 31 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      __default__.kill_mission = 0;
//#line 31 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      Mission.abstract_parameters.push_back(MultiDroneManagerConfig::AbstractParamDescriptionConstPtr(new MultiDroneManagerConfig::ParamDescription<bool>("kill_mission", "bool", 0, "start and stop mission", "", &MultiDroneManagerConfig::kill_mission)));
//#line 31 "/home/cc/ee106b/sp23/class/ee106b-abr/Desktop/drone_workspace/src/qrotor_firmware-devel/qrotor_ground/cfg/MultiDroneManager.cfg"
      __param_descriptions__.push_back(MultiDroneManagerConfig::AbstractParamDescriptionConstPtr(new MultiDroneManagerConfig::ParamDescription<bool>("kill_mission", "bool", 0, "start and stop mission", "", &MultiDroneManagerConfig::kill_mission)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Mission.convertParams();
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(MultiDroneManagerConfig::AbstractGroupDescriptionConstPtr(new MultiDroneManagerConfig::GroupDescription<MultiDroneManagerConfig::DEFAULT::MISSION, MultiDroneManagerConfig::DEFAULT>(Mission)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(MultiDroneManagerConfig::AbstractGroupDescriptionConstPtr(new MultiDroneManagerConfig::GroupDescription<MultiDroneManagerConfig::DEFAULT::MISSION, MultiDroneManagerConfig::DEFAULT>(Mission)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(MultiDroneManagerConfig::AbstractGroupDescriptionConstPtr(new MultiDroneManagerConfig::GroupDescription<MultiDroneManagerConfig::DEFAULT, MultiDroneManagerConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<MultiDroneManagerConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<MultiDroneManagerConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<MultiDroneManagerConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    MultiDroneManagerConfig __max__;
    MultiDroneManagerConfig __min__;
    MultiDroneManagerConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const MultiDroneManagerConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static MultiDroneManagerConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &MultiDroneManagerConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const MultiDroneManagerConfig &MultiDroneManagerConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const MultiDroneManagerConfig &MultiDroneManagerConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const MultiDroneManagerConfig &MultiDroneManagerConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<MultiDroneManagerConfig::AbstractParamDescriptionConstPtr> &MultiDroneManagerConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<MultiDroneManagerConfig::AbstractGroupDescriptionConstPtr> &MultiDroneManagerConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const MultiDroneManagerConfigStatics *MultiDroneManagerConfig::__get_statics__()
  {
    const static MultiDroneManagerConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = MultiDroneManagerConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __MULTIDRONEMANAGERRECONFIGURATOR_H__
