(cl:defpackage qrotor_firmware-srv
  (:use )
  (:export
   "FLATTRAJECTORY"
   "<FLATTRAJECTORY-REQUEST>"
   "FLATTRAJECTORY-REQUEST"
   "<FLATTRAJECTORY-RESPONSE>"
   "FLATTRAJECTORY-RESPONSE"
   "SETPOINT"
   "<SETPOINT-REQUEST>"
   "SETPOINT-REQUEST"
   "<SETPOINT-RESPONSE>"
   "SETPOINT-RESPONSE"
  ))

