// Generated by gencpp from file qrotor_firmware/AttitudeState.msg
// DO NOT EDIT!


#ifndef QROTOR_FIRMWARE_MESSAGE_ATTITUDESTATE_H
#define QROTOR_FIRMWARE_MESSAGE_ATTITUDESTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Quaternion.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace qrotor_firmware
{
template <class ContainerAllocator>
struct AttitudeState_
{
  typedef AttitudeState_<ContainerAllocator> Type;

  AttitudeState_()
    : header()
    , quaternion()
    , body_rates()
    , angular_acceleration()  {
    }
  AttitudeState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , quaternion(_alloc)
    , body_rates(_alloc)
    , angular_acceleration(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _quaternion_type;
  _quaternion_type quaternion;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _body_rates_type;
  _body_rates_type body_rates;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _angular_acceleration_type;
  _angular_acceleration_type angular_acceleration;





  typedef boost::shared_ptr< ::qrotor_firmware::AttitudeState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qrotor_firmware::AttitudeState_<ContainerAllocator> const> ConstPtr;

}; // struct AttitudeState_

typedef ::qrotor_firmware::AttitudeState_<std::allocator<void> > AttitudeState;

typedef boost::shared_ptr< ::qrotor_firmware::AttitudeState > AttitudeStatePtr;
typedef boost::shared_ptr< ::qrotor_firmware::AttitudeState const> AttitudeStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qrotor_firmware::AttitudeState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qrotor_firmware::AttitudeState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::qrotor_firmware::AttitudeState_<ContainerAllocator1> & lhs, const ::qrotor_firmware::AttitudeState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.quaternion == rhs.quaternion &&
    lhs.body_rates == rhs.body_rates &&
    lhs.angular_acceleration == rhs.angular_acceleration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::qrotor_firmware::AttitudeState_<ContainerAllocator1> & lhs, const ::qrotor_firmware::AttitudeState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace qrotor_firmware

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::qrotor_firmware::AttitudeState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qrotor_firmware::AttitudeState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qrotor_firmware::AttitudeState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qrotor_firmware::AttitudeState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qrotor_firmware::AttitudeState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qrotor_firmware::AttitudeState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qrotor_firmware::AttitudeState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9948c65f79422ced49892ff33a8d7940";
  }

  static const char* value(const ::qrotor_firmware::AttitudeState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9948c65f79422cedULL;
  static const uint64_t static_value2 = 0x49892ff33a8d7940ULL;
};

template<class ContainerAllocator>
struct DataType< ::qrotor_firmware::AttitudeState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qrotor_firmware/AttitudeState";
  }

  static const char* value(const ::qrotor_firmware::AttitudeState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qrotor_firmware::AttitudeState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# AttitudeState msg\n"
"std_msgs/Header             header\n"
"geometry_msgs/Quaternion    quaternion\n"
"geometry_msgs/Vector3       body_rates\n"
"geometry_msgs/Vector3       angular_acceleration\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::qrotor_firmware::AttitudeState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qrotor_firmware::AttitudeState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.quaternion);
      stream.next(m.body_rates);
      stream.next(m.angular_acceleration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AttitudeState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qrotor_firmware::AttitudeState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qrotor_firmware::AttitudeState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "quaternion: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.quaternion);
    s << indent << "body_rates: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.body_rates);
    s << indent << "angular_acceleration: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.angular_acceleration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QROTOR_FIRMWARE_MESSAGE_ATTITUDESTATE_H
