// Generated by gencpp from file qrotor_firmware/FlatTrajectoryResponse.msg
// DO NOT EDIT!


#ifndef QROTOR_FIRMWARE_MESSAGE_FLATTRAJECTORYRESPONSE_H
#define QROTOR_FIRMWARE_MESSAGE_FLATTRAJECTORYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qrotor_firmware
{
template <class ContainerAllocator>
struct FlatTrajectoryResponse_
{
  typedef FlatTrajectoryResponse_<ContainerAllocator> Type;

  FlatTrajectoryResponse_()
    : success(false)  {
    }
  FlatTrajectoryResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::qrotor_firmware::FlatTrajectoryResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qrotor_firmware::FlatTrajectoryResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FlatTrajectoryResponse_

typedef ::qrotor_firmware::FlatTrajectoryResponse_<std::allocator<void> > FlatTrajectoryResponse;

typedef boost::shared_ptr< ::qrotor_firmware::FlatTrajectoryResponse > FlatTrajectoryResponsePtr;
typedef boost::shared_ptr< ::qrotor_firmware::FlatTrajectoryResponse const> FlatTrajectoryResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qrotor_firmware::FlatTrajectoryResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qrotor_firmware::FlatTrajectoryResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::qrotor_firmware::FlatTrajectoryResponse_<ContainerAllocator1> & lhs, const ::qrotor_firmware::FlatTrajectoryResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::qrotor_firmware::FlatTrajectoryResponse_<ContainerAllocator1> & lhs, const ::qrotor_firmware::FlatTrajectoryResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace qrotor_firmware

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::qrotor_firmware::FlatTrajectoryResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qrotor_firmware::FlatTrajectoryResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qrotor_firmware::FlatTrajectoryResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qrotor_firmware::FlatTrajectoryResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qrotor_firmware::FlatTrajectoryResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qrotor_firmware::FlatTrajectoryResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qrotor_firmware::FlatTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::qrotor_firmware::FlatTrajectoryResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::qrotor_firmware::FlatTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qrotor_firmware/FlatTrajectoryResponse";
  }

  static const char* value(const ::qrotor_firmware::FlatTrajectoryResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qrotor_firmware::FlatTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::qrotor_firmware::FlatTrajectoryResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qrotor_firmware::FlatTrajectoryResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FlatTrajectoryResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qrotor_firmware::FlatTrajectoryResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qrotor_firmware::FlatTrajectoryResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QROTOR_FIRMWARE_MESSAGE_FLATTRAJECTORYRESPONSE_H
