(cl:in-package qrotor_firmware-msg)
(cl:export '(HEADER-VAL
          HEADER
          EULER-VAL
          EULER
          BODY_RATES-VAL
          BODY_RATES
          LINEAR_ACCELERATION-VAL
          LINEAR_ACCELERATION
          ANGULAR_ACCELERATION-VAL
          ANGULAR_ACCELERATION
          CMD_EULER-VAL
          CMD_EULER
          THRUST-VAL
          THRUST
          MOMENT-VAL
          MOMENT
          POSITION-VAL
          POSITION
          VELOCITY-VAL
          VELOCITY
          LOOP_RATE-VAL
          LOOP_RATE
          VOLTAGE-VAL
          VOLTAGE
          CURRENT-VAL
          CURRENT
          ESC_IN_US-VAL
          ESC_IN_US
          MOTORS_STATE-VAL
          MOTORS_STATE
          CONTROL_MODE-VAL
          CONTROL_MODE
          FIRMWARE_TIME-VAL
          FIRMWARE_TIME
          ATTITUDE_MODE-VAL
          ATTITUDE_MODE
          LYAPUNOV-VAL
          LYAPUNOV
))